version: '3.7'
services:
  app:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling -d /tmp/website
    volumes:
      - $PWD:/srv/jekyll
      - bundle_data:/usr/local/bundle
    ports:
      - 4000:4000
volumes:
  bundle_data:
    driver: local
